### ISSUE TITLE
.row last-child selector for .col-* will not work in certain cases

### ISSUE THREAD

**Issue by jsonkao** [stuyspec/stuyspec.com#28]
```
<div class="row">
   <div class="col-lg-4"></div>
   <div class="col-lg-3"></div>
   <div class="col-lg-5"></div>
   <p class="something">hello</div>
</div>
```
Selecting the last column to remove gutter margins on the right will not work with current CSS selectors. No apparent solution until CSS selectors level 4 is accepted and implemented by browsers, where we will have access to `:nth-match(selector)` and `:nth-last-match(selector)`.

**Comment by jkao1** [comment]
Using <a href="https://stackoverflow.com/a/8539107/6174302">this solution</a> works for first children, but not last children. For now, we will use a standard last-child, which will not work in the example above but will work in most cases.

**Comment by guilhermemarconi** [comment]
Have you tried `:last-of-type`?

**Comment by jkao1** [comment]
I was under the impression that `:last-of-type` would only work with element types, not classes.

**Comment by guilhermemarconi** [comment]
Can you show me an example of why you want to remove the right margin?
BS3 makes a good work with the `.row > .col-*` selectors.

**Comment by jkao1** [comment]
In general, the left and right margins are problematic because our gutters are already defined with padding. Because our layout is complicated, there can be several nested layers of `Row`'s and `Col`'s. Having that left/right margin would create a second gutter (our first already defined with padding), leading to either excess or incorrect/unintended spacing. An example:

![image](https://user-images.githubusercontent.com/15334952/31862181-d484c7c8-b707-11e7-86ef-b5e4cca5211f.png)

The red-orange highlights are the columns. If there were margins on the left and right, the page would be un-aesthetically skinnier than the masthead.

**Comment by guilhermemarconi** [comment]
I get it, but you should let BS take care of the columns (and its gutters) and use another element inside of each column, when needed, that will have its own `margin`/`padding` from the other columns.
It's safer and quicker, because you don't have to change the BS behaviour.

Think in BS taking care of its own business: the columns. What is inside of them (and all the rest of the project) is on you. So, you can add the style as you want to.

**Comment by vs2961** [comment]
This is an old issue, will reopen if something in here is needed.
