### ISSUE TITLE
Toggling dark mode when in an article crashes the website and requires a reload to fix

### ISSUE THREAD

**Issue by pserb** [stuyspec/stuyspec.com#351]
Has to do with the ad implemented on the bottom

webpage looks like this after toggle:
![image](https://user-images.githubusercontent.com/61565464/132154620-2a3cfba8-6d39-4327-99e0-ae1700d8fff7.png)

**Comment by AndySok** [comment]
the issue is outlined in [this stackoverflow thread.](https://stackoverflow.com/questions/35338314/adsense-error-with-joomla-adsbygoogle-push-error)

What essentially happens is there are too many ad requests and the website cannot handle that. There's a fix involving [google tags](https://support.google.com/dfp_sb/answer/2694377?visit_id=1-636301421618198678-920866889&rd=1). I will fix the issue ASAP, as it is affecting not only darkmode but also opening different articles on the website
